title: Evan Douglas # your site title
author: Evan Douglas
email: eadouglas97@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Evan Douglas Personal Website
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://evandouglas.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  evandouglas # replace with your_github_username or comment to remove link from footer
linkedin_url: https://www.linkedin.com/in/evan-douglas-2b796012a/
social:
  name: Evan Douglas
  links:
    - https://www.linkedin.com/in/evan-douglas-2b796012a/
    - https://github.com/evandouglas

disqus:
  shortname:  # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
custom_theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
